//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationHeuristicWcfService.HeuristicService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HeuristicService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllocations", ReplyAction="http://tempuri.org/IService1/GetAllocationsResponse")]
        TaskAllocationLibrary.TaskAllocationOutput[] GetAllocations(TaskAllocationLibrary.TaskAllocationInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllocations", ReplyAction="http://tempuri.org/IService1/GetAllocationsResponse")]
        System.Threading.Tasks.Task<TaskAllocationLibrary.TaskAllocationOutput[]> GetAllocationsAsync(TaskAllocationLibrary.TaskAllocationInput input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AllocationHeuristicWcfService.HeuristicService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AllocationHeuristicWcfService.HeuristicService.IService1>, AllocationHeuristicWcfService.HeuristicService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TaskAllocationLibrary.TaskAllocationOutput[] GetAllocations(TaskAllocationLibrary.TaskAllocationInput input) {
            return base.Channel.GetAllocations(input);
        }
        
        public System.Threading.Tasks.Task<TaskAllocationLibrary.TaskAllocationOutput[]> GetAllocationsAsync(TaskAllocationLibrary.TaskAllocationInput input) {
            return base.Channel.GetAllocationsAsync(input);
        }
    }
}
