//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.AWSHeuristicServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AWSHeuristicServiceReference.IHeuristicService")]
    public interface IHeuristicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeuristicService/GetAllocations", ReplyAction="http://tempuri.org/IHeuristicService/GetAllocationsResponse")]
        TaskAllocationLibrary.TaskAllocationOutput[] GetAllocations(TaskAllocationLibrary.TaskAllocationInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeuristicService/GetAllocations", ReplyAction="http://tempuri.org/IHeuristicService/GetAllocationsResponse")]
        System.Threading.Tasks.Task<TaskAllocationLibrary.TaskAllocationOutput[]> GetAllocationsAsync(TaskAllocationLibrary.TaskAllocationInput input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeuristicServiceChannel : GUI.AWSHeuristicServiceReference.IHeuristicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeuristicServiceClient : System.ServiceModel.ClientBase<GUI.AWSHeuristicServiceReference.IHeuristicService>, GUI.AWSHeuristicServiceReference.IHeuristicService {
        
        public HeuristicServiceClient() {
        }
        
        public HeuristicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeuristicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeuristicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeuristicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TaskAllocationLibrary.TaskAllocationOutput[] GetAllocations(TaskAllocationLibrary.TaskAllocationInput input) {
            return base.Channel.GetAllocations(input);
        }
        
        public System.Threading.Tasks.Task<TaskAllocationLibrary.TaskAllocationOutput[]> GetAllocationsAsync(TaskAllocationLibrary.TaskAllocationInput input) {
            return base.Channel.GetAllocationsAsync(input);
        }
    }
}
